import { Footer, Header } from "../components/layout";
import "./globals.css";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col justify-between min-h-screen">
          <div>
            <header className="sticky top-0  w-full mb-5">
              <Header />
            </header>
            <main className={`${styles.main} gap-9 pr-80 pl-5`}>
              {children}
            </main>
          </div>
          <footer>
            <Header />
          </footer>
        </div>
      </body>
    </html>
  );
}
